### PR TITLE
Jjg/sabbath

### PR DESCRIPTION
**Pull request by jgonz3**

### CODE REVIEW

**Comment by jgonz3** [comment]
Please check the dropped paragraphs in the changelog and let me know what you think about the choice. I actually love that kind of information and feel bad about editing them out.

**Review by mvahowe — COMMENTED** [review]
Commit changelog is working really well for me!

> This picture of the Creator as a manual laborer is one the Bible often paints.

"The Bible also speaks of God the creator as a manual laborer"

> Of all of God’s instructions, they were spoken

"these were spoken"

>  Give freely without begrudging it

"Give freely and willingly"

> Jesus’s Sabbath healings were going to clash

"clashed"

**Comment by jgonz3** [comment]
How about “The Bible **often** speaks of God the creator as a manual laborer?” It’s closer to meaning of the original text.

**Review by mvahowe — APPROVED** [review]
LGTM

**Pull request merged**
