### PR TITLE
Jjg/lords supperthe

### PR DESCRIPTION
**Pull request by jgonz3**

### CODE REVIEW

**Comment by jgonz3** [comment]
Beware: I edited out a lot of occurrences of the word “remembrance,” especially in the context of the protestant view.

I'm not certain of that choice and would appreciate your feedback about it.

Perhaps it should be documented in the “major changes” section in the change log?

**Review by mvahowe — COMMENTED** [review]
> Many see the Lord’s Supper hinted

"many see the Lord's supper behind..."

**Review by mvahowe — COMMENTED** [review]
> alludes to

"refers to"

> they partook of food with glad and generous hearts

There must be a more modern translation of this!

**Comment by mvahowe** [comment]
AFAICS you removed the non-technical uses of "remembrance" which I think is good, in an article where there's also a technical sense (that you left in).

In general, I think it would be useful to document terms, expressions etc that we changed (or didn't change) and that are likely to come up again. eg
- leave "ark" and "tabernacle" (proper nouns)
- remembrance (except when specifically describing the Lord's Supper) => thankfulness

**Comment by jgonz3** [comment]
> they partook of food with glad and generous hearts

How about: “gladly and generously shared their food with each other”
Bear in mind that this is a quoted Bible verse, though.

**Comment by mvahowe** [comment]
> > they partook of food with glad and generous hearts
> 
> How about: “gladly and generously shared their food with each other” Bear in mind that this is a quoted Bible verse, though.

I'm suggesting we quote from a modern translation (which is fair use for isolated verses and what TBD already does. Good News Bible?

**Comment by jgonz3** [comment]
> I'm suggesting we quote from a modern translation (which is fair use for isolated verses and what TBD already does. Good News Bible?

Done 👍

**Review by mvahowe — APPROVED** [review]
Fixed merge conflict

**Pull request merged**
