### PR TITLE
Adapt JesusChrist article + Add the corresponding changelog

### PR DESCRIPTION
**Pull request by jgonz3**

### CODE REVIEW

**Review by mvahowe — COMMENTED** [review]
Armed with an extra-large cup of tea...

> Matthew, presents Jesus

Lose the comma which is left over from the edit.

> Mark emphasises Jesus as the servant of all

"emphasises" is not something you generally to do a person. "Mark reveals Jesus" ? (I think TBD is just trying not to repeat terms here so I don't think that the exact verb matters much.)

> the main stages of events of the life of Jesus

the main events in the life of Jesus

> These stages show a clear progression

There is a clear...

> showing that salvation is for all the nations

Excellent!

> both feature genealogies

"include" ?

> creative imaginations

"creative ideas" ? "theories" ? (Both those things are the product of a creative imagination which is a characteristic of a person)

> coming of the kingdom, just as

"coming of the kingdom as..." Or "It is important to note that John the Baptist and Jesus started their ministries with the same message of the coming kingdom".

> he didn't need repentance, as evidenced in the NT.

He had no need to repent. The NT supports this claim.

> The most important part of Jesus’s baptism was the voice

What? Why? Breathe deeply...

> This God given announcement 

"God-given"

> It wasn’t just an inner experience that Jesus had.

Jesus's baptism was not just about an inner experience.

> Though not much emphasized in the Gospels, the ministry of Jesus Christ cannot be fully understood without the activity of the Spirit.

"The baptism of Jesus shows the importance of the Spirit in his ministry. The general lack of emphasis on the Spirit in the gospels does not change this."

> Jesus’s whole ministry was characterized by confrontation with adverse spiritual forces.

I prefer the original active voice. But we could simplify to "Jesus confronted adverse spiritual forces throughout his ministry".

> This took place in the context of John the Baptist’s

"The context for this was"

More to follow...

**Comment by mvahowe** [comment]
> John’s account indicates Jesus 

"indicates that"

> who later would become totally dependent

"who later became"

> The Sermon on the Mount may give us a good idea

"gives us..." (I don't think that "may be taken" is a conditional)

> This popularity doesn’t prove the spiritual purpose

I think the original sense is closer to "However, those people did not grasp the spiritual purpose of Jesus's mission"

> Jesus warned his disciples against burden themselves

"burdening themselves" or maybe "weighing themselves down"

> The last one is notable

"The first one" (the faith of the centurion)

> In Nazareth, the people of his hometown were so hostile

"In Nazareth, his hometown, people were..."

> Jesus had great popularity at this stage

"Jesus was very popular"

> and possible to the one Jesus claimed to be.

"and is perfectly possible if Jesus is who he claimed to be."

> Peter was used by God to let both Jews and Gentiles enter into the church

"... to bring both Jews and Gentiles into..."

> and enhancing the gospel with loving dedication

I have no idea what this means before or after the edit!

> All four Gospels relate Jesus entering into Jerusalem

"describe"

> that his body was broken and that his blood was poured out for others

"that his body would be broken and that his blood would be poured out for others"

> Popular support was soon to be over

"Jesus would soon lose his popular support"

> as if nature itself were acknowledging

"as if nature itself recognised"

> Jesus’s behaviour towards them clearly continued to look the same.

The disciples were able to recognise the risen Jesus as the man they had known before.

I feel like there's another year's work to do on this article, but let's try to pull it to conclusion. Thanks for your heroic efforts!

**Comment by jgonz3** [comment]
Thanks Mark, lots of good changes. How about the following?

> "creative ideas" ? "theories" ?

“creative stories”

> "coming of the kingdom as..." Or "It is important to note that John the Baptist and Jesus started their ministries with the same message of the coming kingdom".

The author believes in a sense that Jesus “picked-up” the message John had been preaching all along. So how about: “It is important to note that Jesus started his ministry with the same message of the coming kingdom that John the Baptist announced”

> Jesus's baptism was not just about an inner experience.

I assume that in the context the author is referring to the coming down of the Holy Spirit, not the whole baptism experience. Perhaps some might think that Jesus had an inner experience regarding the Spirit, due the the fact that Matthew and Mark state that “he” saw the Spirit coming down like a dove. But Luke doesn't say “he”, suggesting it was public, and John reports that the baptist testified that he saw the Spirit coming down like a dove too.
So I suggest: “(…), which was not just an inner experience for Jesus.”
Please feel free to disagree, and I'll take your suggestion in instead.

> Jesus warned his disciples against burden themselves

Oops! I had meant “Jesus warned his disciples not to burden themselves”

**Comment by mvahowe** [comment]
> “creative stories”

ok
 
> The author believes in a sense that Jesus “picked-up” the message John had been preaching all along. So how about: “It is important to note that Jesus started his ministry with the same message of the coming kingdom that John the Baptist announced”

ok
 
> which was not just an inner experience for Jesus.

that works for me.

> Jesus warned his disciples not to burden themselves

also works for me.

**Pull request merged**
