### PR TITLE
Adapt Scribe article

### PR DESCRIPTION
**Pull request by jgonz3**

### CODE REVIEW

**Comment by jgonz3** [comment]
Please check out the branch to compare with the original article in Oxygen. Once there, I find comparing in the _author_ view easier. But the comments I added in are only visible in the _text_ view, so make sure to check both.
Thank you 🙂

**Review by mvahowe — COMMENTED** [review]
Lots of good changes here. I'd be happy to be more radical in simplifying certain phrases.

As with the other PR, I think comments needs to be outside the document itself. (The biggest change, in terms of characters, is the markup for the comments that isn't actually a change.) I think we could make, say, a `changelog` directory with the same structure as for the articles, and summarise changes for each article there. (I don't think we need to document every single change, just major decisions. As with comments in code, we don't need to document *what* happened - that's what diff does - we need to document *why* we did it.)

`<span class="sc">nlt</span>` is a reference to NLT which doesn't translate, so we should remove this.

"From then and onwards" => "from that point" (the original doesn't seem bad to me)

"men of law" => "men of the Law" ?

"mingling" => "mixing" ?

"They are frequently found attempting to trick" => "They frequently try to trick" ?

"In his reprimands to *the* them"

"They outwardly appeared to be outwardly"

**Comment by jgonz3** [comment]
I've made several changes according to your feedback and I've added the `changelog` directory with an `S/Scribe.md` file to document the major changes.

Let me know what you think about it.

Thanks.

**Review by mvahowe — APPROVED** [review]
This looks good to me. I wonder about some of the details but it really makes more sense to get something to the translators and await their feedback. The summary looks perfect to me - a clear summary without getting lost in the details.

**Pull request merged**
