### PR TITLE
Jop/wrath of god

### PR DESCRIPTION
**Pull request by joannapierquin**

### CODE REVIEW

**Review by JonathanS77 — CHANGES_REQUESTED** [review]
line 7: wanton rebellion. Synonym for wanton?

**Comment by joannapierquin** [comment]
> line 7: wanton rebellion. Synonym for wanton?

Which synonym should we use?
reckless rebellion ? 
Excessive rebellion ?

**Review by JonathanS77 — APPROVED** [review]
line 7: replace "wanton rebellion" by "deliberate rebellion"

**Review by JonathanS77 — COMMENTED** [review]
LGTM

**Pull request merged**
